//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YugensysAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YugensysDBEntities : DbContext
    {
        public YugensysDBEntities()
            : base("name=YugensysDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_pair> tbl_pair { get; set; }
        public virtual DbSet<tbl_suggested> tbl_suggested { get; set; }
    
        public virtual ObjectResult<suggested_sp_Result> suggested_sp(string color)
        {
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<suggested_sp_Result>("suggested_sp", colorParameter);
        }
    }
}
